import mongoose from 'mongoose';

// Array of chat members + _id (autogenerated)
// Unique for now, if expanded to have a chat admin this feature isnt good (Ez to fix tho)
const chatSchema = new mongoose.Schema(
    {
    members: { type: Array, required: true, unique: true }
    },
    { timestamps: true }
);

const Chat = mongoose.model("Chat", chatSchema);

export default Chat;